StartupEvents.registry("fluid",e=>{
    e.create('gensokyo_mechanician:slime_fluid').thickTexture(0X6bf059).displayName('史莱姆黏液')
    e.create('gensokyo_mechanician:slime_aluminum_oxide_fluid').thickTexture(0Xc2f4bc).displayName('史莱姆氧化铝溶液')
    e.create('gensokyo_mechanician:slime_aluminum_fluid').thickTexture(0Xa9f69e).displayName('史莱姆铝溶液')
    e.create('gensokyo_mechanician:molten_chromium').displayName('熔融铬')
    .stillTexture('gensokyo_mechanician:block/chromium_still')
    .flowingTexture('gensokyo_mechanician:block/chromium_flowing')
    .bucketColor(0Xa9a9a9)
    .luminosity(15)

    e.create('gensokyo_mechanician:nether_acid').thinTexture(0X88001b).displayName('下界酸')
    e.create('gensokyo_mechanician:copper_ion_solution').thinTexture(0Xce6e52).displayName('铜离子浸出液')
    e.create('gensokyo_mechanician:tin_ion_solution').thinTexture(0Xdfddd7).displayName('锡离子浸出液')
    e.create('gensokyo_mechanician:zinc_ion_solution').thinTexture(0Xa5c0a0).displayName('锌离子浸出液')
    e.create('gensokyo_mechanician:iron_ion_solution').thinTexture(0Xb7383d).displayName('铁离子浸出液')
    e.create('gensokyo_mechanician:gold_ion_solution').thinTexture(0Xfbdd19).displayName('金离子浸出液')
    e.create('gensokyo_mechanician:nickel_ion_solution').thinTexture(0Xc39a73).displayName('镍离子浸出液')
    e.create('gensokyo_mechanician:aluminum_ion_solution').thinTexture(0Xe7dacf).displayName('铝离子浸出液')
    e.create('gensokyo_mechanician:chromium_ion_solution').thinTexture(0Xbababa).displayName('铬离子浸出液')
    e.create('gensokyo_mechanician:blaze_compound').displayName('烈焰化合物')
    .stillTexture('gensokyo_mechanician:block/blaze_compound_still')
    .flowingTexture('gensokyo_mechanician:block/blaze_compound_flowing')
    .bucketColor(0Xffc400)
    .luminosity(15)

    e.create('gensokyo_mechanician:coal_tar').thinTexture(0X3c2716).displayName('煤焦油')

    e.create('gensokyo_mechanician:mineral_enrichment_fluid').thickTexture(0Xa9a9a9).displayName('矿物富集泥浆')
    
    e.create('gensokyo_mechanician:cooling_fluid').thinTexture(0X3843ed).displayName('热交换液')
    e.create('gensokyo_mechanician:asphalt').thinTexture(0X212121).displayName('沥青')
    e.create('gensokyo_mechanician:redstone_acid').thinTexture(0Xec4147).displayName('红石酸')
    e.create('gensokyo_mechanician:copper_extraction_fluid').thickTexture(0Xb4d10e).displayName('铜萃取液')
    e.create('gensokyo_mechanician:tin_extraction_fluid').thickTexture(0Xa8e2b8).displayName('锡萃取液')
    e.create('gensokyo_mechanician:zinc_extraction_fluid').thickTexture(0X8de58a).displayName('锌萃取液')
    e.create('gensokyo_mechanician:soul_solution').thinTexture(0Xf0f0f0).displayName('灵魂溶液')
    e.create('gensokyo_mechanician:ender_fluid').thinTexture(0X258474).displayName('熔融末影珍珠')
    e.create('gensokyo_mechanician:ender_fuel_fluid').thinTexture(0X0b4d42).displayName('末影燃油')
})