StartupEvents.registry('item',e=>{
    e.create('gensokyo_mechanician:refractory_brick','basic')
    e.create('gensokyo_mechanician:dirty_tin_dust','basic')
    e.create('gensokyo_mechanician:tin_dust','basic')
    e.create('gensokyo_mechanician:crushed_andesite','basic')
    e.create('gensokyo_mechanician:andesite_dust','basic')
    e.create('gensokyo_mechanician:dirty_nickel_dust','basic').displayName('污浊的镍粉')
    e.create('gensokyo_mechanician:nickel_dust','basic').displayName('镍粉')
    e.create('gensokyo_mechanician:dirty_aluminum_ore_dust','basic').displayName('污浊的铝土粉')
    e.create('gensokyo_mechanician:aluminum_ore_dust','basic').displayName('铝土粉')
    e.create('gensokyo_mechanician:aluminum_oxide_dust','basic').displayName('氧化铝粉')
    e.create('gensokyo_mechanician:aluminum_dust','basic').displayName('铝粉')
    e.create('gensokyo_mechanician:chromate_dust','basic').displayName('铬酸盐粉')
    e.create('gensokyo_mechanician:chromium_oxide_dust','basic').displayName('氧化铬粉')
    e.create('gensokyo_mechanician:chromium_dust','basic').displayName('铬粉')
    e.create('gensokyo_mechanician:tungstic_acid_dust','basic').displayName('钨酸粉')
    e.create('gensokyo_mechanician:raw_iron_ingot','basic')
    e.create('gensokyo_mechanician:raw_steel_ingot','basic')
    e.create('gensokyo_mechanician:industrial_magma_cream','basic')
    e.create('gensokyo_mechanician:tungsten_mold_empty','basic')
    e.create('gensokyo_mechanician:tungsten_mold_filled','basic')

    e.create('gensokyo_mechanician:gun_mechanism','basic')
    e.create('gensokyo_mechanician:brass_shell','basic')
    e.create('gensokyo_mechanician:large_brass_shell','basic')
    e.create('gensokyo_mechanician:gas_head','basic')
    e.create('gensokyo_mechanician:slap_head','basic')
    e.create('gensokyo_mechanician:slap_core','basic')
    e.create('gensokyo_mechanician:rbapb_head','basic')
    e.create('gensokyo_mechanician:rbapb_core','basic')
    e.create('gensokyo_mechanician:gernade_head','basic')
    e.create('gensokyo_mechanician:ap_head','basic')
    e.create('gensokyo_mechanician:ap_core','basic')
    e.create('gensokyo_mechanician:gunpowder_small','basic')
    e.create('gensokyo_mechanician:cooling_plate','basic')
    e.create('gensokyo_mechanician:helmetlining','basic')

    e.create('gensokyo_mechanician:ball_bearing','basic')
    e.create('gensokyo_mechanician:circuit_board','basic')
    e.create('gensokyo_mechanician:integrated_circuit','basic')
    e.create('gensokyo_mechanician:integrated_circuit_board','basic')
    e.create('gensokyo_mechanician:steel_ball','basic')
    e.create('gensokyo_mechanician:quartz_dust','basic')
    e.create('gensokyo_mechanician:rose_quartz_dust','basic')
    e.create('gensokyo_mechanician:lapis_sheet','basic')

    e.create('gensokyo_mechanician:vein_prospector','basic').displayName('百百世的探矿杖')
    e.create('gensokyo_mechanician:copper_berries','basic')
    e.create('gensokyo_mechanician:tin_berries','basic')
    e.create('gensokyo_mechanician:zinc_berries','basic')
    e.create('gensokyo_mechanician:experience_berries','basic')

    e.create('gensokyo_mechanician:nether_star_catalyst','basic').glow(true)
    e.create('gensokyo_mechanician:crimson_biomass','basic')
    e.create('gensokyo_mechanician:warped_biomass','basic')
    e.create('gensokyo_mechanician:wither_spore','basic')
    e.create('gensokyo_mechanician:netherite_composite_board','basic')

    e.create('gensokyo_mechanician:ender_port','basic').displayName('末影接口')
    e.create('gensokyo_mechanician:void_port','basic').displayName('虚空接口')
    e.create('gensokyo_mechanician:ender_matter_positive','basic').displayName('阳极末影')
    e.create('gensokyo_mechanician:ender_matter_negative','basic').displayName('阴极末影')
    e.create('gensokyo_mechanician:graviton_circuit_board','basic').displayName('真空阵列板')
    e.create('gensokyo_mechanician:void_matter_a','basic').displayName('虚空粒子α')
    e.create('gensokyo_mechanician:void_matter_b','basic').displayName('虚空粒子β')
    e.create('gensokyo_mechanician:void_matter_y','basic').displayName('虚空粒子γ')

    e.create('gensokyo_mechanician:aluminum_armor_plate','basic').displayName('铝插板').maxDamage(100).tag("protection_pixel:plates")
    e.create('gensokyo_mechanician:steel_armor_plate','basic').displayName('钢插板').maxDamage(100).tag("protection_pixel:plates")
    e.create('gensokyo_mechanician:pearlescent_armor_plate','basic').displayName('珠光插板').maxDamage(100).tag("protection_pixel:plates")
    e.create('gensokyo_mechanician:naga_armor_plate','basic').displayName('娜迦插板').maxDamage(100).tag("protection_pixel:plates")
    e.create('gensokyo_mechanician:knightmetal_armor_plate','basic').displayName('骑士金属插板').maxDamage(100).tag("protection_pixel:plates")
    e.create('gensokyo_mechanician:fiery_armor_plate','basic').displayName('炽铁插板').maxDamage(100).tag("protection_pixel:plates")
    e.create('gensokyo_mechanician:yeti_armor_plate','basic').displayName('雪怪插板').maxDamage(100).tag("protection_pixel:plates")

})